### PR TITLE
Fixes #371 : webapp crashes when unicode text is returned as response

### LINKED ISSUE #371: webapp crashes when unicode text is returned as response
Code to reproduce the bug is available at

https://gist.github.com/anandology/72168ffbf33e87ebcfb419d12fd5e7cd

It crashes with the following error.

	UnicodeEncodeError('latin-1', '\u0c05\u0c06', 0, 2, 'ordinal not in range(256)')
	Traceback (most recent call last):
	  File "/Users/anand/github/webpy/webpy/web/wsgiserver/wsgiserver3.py", line 1089, in communicate
	    req.respond()
	  File "/Users/anand/github/webpy/webpy/web/wsgiserver/wsgiserver3.py", line 877, in respond
	    self.server.gateway(self).respond()
	  File "/Users/anand/github/webpy/webpy/web/wsgiserver/wsgiserver3.py", line 1991, in respond
	    chunk = chunk.encode('ISO-8859-1')
	UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)

cc: @Zashas

### PR DESCRIPTION
**Pull request by Zashas**
In Py3, the data of the response sent to the WSGI server is now always in UTF8-encoded bytes.
I had to modify a bit the Browser class for it to handle this change.

### CODE REVIEW

**Comment by Zashas** [comment]
Woops, kinda messed my branch. This PR includes another bugfix. Merging shoudn't be an issue.

**Comment by Zashas** [comment]
I found a bug with this PR using Py2, I'll fix it ASAP.

**Comment by Zashas** [comment]
Fixed. Patch should work correctly.

**Comment by anandology** [comment]
Looks like with this patch, the app will fail if bytes are returned from the app. There are genuine cases where bytes need to be returned like sending back an image etc.

**Comment by Zashas** [comment]
Now all the WSGI layers should use bytes for storing and sending the response. I've written two unittests to ensure that it works. A view can now return either bytes, a string or a unicode string (in Py2) and it should flawlessy be encoded into bytes and properly served. 

This PR also includes a fix for issue #372. I've added a whitelist of AST nodes instead of a blacklist. Yet I couldn't find a proper list of all Python's AST nodes so it's possible false-alerts could be raised in some complex templates. I'd appreciate if someone could test this whitelist with his own templates.

**Comment by anandology** [comment]
Thanks @Zashas. That looks good to me. 

I think it would be hard to merge your branch directly as it is showing some commits that are already there. Either you can create a new branch and cherry-pick your commits and send a new PR or I can cherry-pick all your changes and merge. If I do that, you'll not be able to get the latest changes to your branch. 

Please let me know which way do you prefer.

**Comment by Zashas** [comment]
I prefer if you cherry-pick and merge them. I'll make a new fresh fork.

Thanks !

**Comment by Zashas** [comment]
I've added one more bugfix.

**Comment by anandology** [comment]
@Zashas cherry-picked all your the commits.

**Comment by Zashas** [comment]
Thanks !

I'm closing this.

**Pull request closed without merging**
