### PR TITLE
Blacken the codebase

### PR DESCRIPTION
**Pull request by cclauss**
Run `black .` so our GitHub Actions tests pass again because that utility is no longer in beta.

### CODE REVIEW

**Comment by cclauss** [comment]
@iredmail Your review, please

**Comment by iredmail** [comment]
- Can we keep Python 3.6? CentOS 7, Ubuntu 18.04 (LTS) still use 3.6.
- There's a unittest failure, would you like to fix it too?

**Comment by cclauss** [comment]
I add py36 again but I am uncertain how to fix the unit test.

**Comment by iredmail** [comment]
I tracked down to Python source file, the `\n` will be removed by `urllib.parse.urlparse()`, so it's safe to remove this unittest in webpy code.

FYI:

- call `urlparse` in web.py `app.request()`: https://github.com/webpy/webpy/blob/06a0b63b0378eb5e188b4d19ef47af0d19074b7d/web/application.py#L214
- call `urlsplit()` inside `urlparse()`: https://github.com/python/cpython/blob/7b5b429adab4fe0fe81858fe3831f06adc2e2141/Lib/urllib/parse.py#L393
- remove unafe chars/bytes in url inside `urlsplit()`: https://github.com/python/cpython/blob/7b5b429adab4fe0fe81858fe3831f06adc2e2141/Lib/urllib/parse.py#L460
- `\n` is one of the unsafe char/byte: https://github.com/python/cpython/blob/7b5b429adab4fe0fe81858fe3831f06adc2e2141/Lib/urllib/parse.py#L82

**Comment by iredmail** [comment]
Please help review my PR #725 
if ok, please help merge, then you can recheck this PR.

**Comment by iredmail** [comment]
Oops, since you added `black` check, my PR failed.
Could you help update your own PR (this thread) with my fix?

**Comment by cclauss** [comment]
@iredmail Please approve and/or merge.

**Review by iredmail — APPROVED** [review]

**Review by iredmail — APPROVED** [review]

**Comment by iredmail** [comment]
Seems I mistakenly quit webpy team and have no privilege to approve. :(

**Comment by iredmail** [comment]
@anandology could you help review and merge? And maybe add me to webpy team (again :( )?

**Pull request merged**
