### PR TITLE
Detect key before `del`.

### PR DESCRIPTION
**Pull request by iredmail**
I personally experienced `KeyError: 'ip'` few times, so might be a good idea to fix it with a `if` condition.

### CODE REVIEW

**Comment by anandology** [comment]
Looking for change of IP is probably a bad idea in itself and that feature in it self can be dropped IMHO.

**Comment by iredmail** [comment]
hi @anandology 

Original code tries to delete key `ip` no matter it exists or not, but it failed few times for me. So i simply add a line to check existence before delete.

I didn't change what the original code do.

**Comment by cclauss** [comment]
`dict.pop("ip", None)` expresses the same idea more compactly.

**Comment by iredmail** [comment]
> `dict.pop("ip", None)` expresses the same idea more compactly.

Thanks for this tip. Updated. :)

**Comment by iredmail** [comment]
Please help review. :)

**Comment by cclauss** [comment]
I believe that @anandology is advocating that we remove `. _validate_ip()` and all code that manipulates `ip` in this class.

**Comment by iredmail** [comment]
I understand. This PR is no harm but fixes one issue. If the best solution is removing some code/feature, then please do it. :)

**Comment by iredmail** [comment]
@cclauss @anandology 
Please help review and merge.

**Comment by iredmail** [comment]
Hi @anandology,

If you have some time, please either merge this PR, or "drop" the feature as mentioned in your first reply in this thread.

**Comment by ohye3166** [comment]
> Hi @anandology,
> 
> If you have some time, please either merge this PR, or "drop" the feature as mentioned in your first reply in this thread.

hello，i meet the same problem， i use your patch and fix it. i don't know why you close it, is there exist a better patch to fix it?

**Comment by iredmail** [comment]
Because no one help review the code, so ...

**Pull request closed without merging**
