### PR TITLE
Support for ssl_certificate_chain

### PR DESCRIPTION
**Pull request by jlguardi**
I've experienced issues with ssl certificates with intermediates. I've exported the necessary params.

### CODE REVIEW

**Comment by jzellman** [comment]
looks good to me, however I don't fully understand the implications to existing users. Could this break them? Or is there a chance where the chain is wrong?

**Comment by jlguardi** [comment]
@jzellman No, it doesn't break anything. It allows the use of certificates with intermediates but it doesn't affect to other certificates.

**Comment by jzellman** [comment]
Thanks @jlguardi  @anandology :ship:

**Comment by jzellman** [comment]
Same as #319

**Comment by anandology** [comment]
CherryPy Webserver has been replaced with Cheroot. Please see http://webpy.org/cookbook/ssl for new instructions.

**Pull request closed without merging**
