### PR TITLE
refactor: run pyupgrade on exists codes

### PR DESCRIPTION
**Pull request by aisk**
The command is `pyupgrade --keep-percent-format --py3-plus`, for we have python 3.5 and upper version support, and I think percent format is not deprecated in near future.

### CODE REVIEW

**Comment by cclauss** [comment]
In general, I try to upgrade to [f-strings](https://www.scivision.dev/python-f-string-speed) as quickly as possible.

**Comment by cclauss** [comment]
Py36 is sunset too.  I would like to drop **both** and add Py310 if @iredmail agrees.
* https://devguide.python.org/devcycle/#end-of-life-branches
* https://devguide.python.org/#status-of-python-branches

**Review by iredmail — COMMENTED** [review]
LGTM

**Review by cclauss — APPROVED** [review]
LGTM.  Thanks for doing this.

**Pull request merged**
