### PR TITLE
some db.py error fix

### PR DESCRIPTION
**Pull request by bigzhu**
1. make sure keys are sorted, keep compare correct in multiple_insert
2. when seqname is not provided guess the seqname will cause error: 
   
   > psycopg2.OperationalError: currval of sequence "xxx" is not yet defined in this session
   
   when you insert id key in postgresql 9.4
   I'm disable the seqname guess, if you need insert return id, must provide seqname. It may cause some problems if you use seqname guess return insert id.

### CODE REVIEW

**Comment by jzellman** [comment]
After looking through the changes, I'm having a hard time seeing the differences since there are a number of diffs that are not part of this change like spacing changes. Could you please revert any erroneous changes to make the diff as small as possible. This will aid merging and will minimize the amount of time needed to review.

**Comment by bigzhu** [comment]
Ok, I will repull this

**Comment by bigzhu** [comment]
@jzellman This bug is fixed in current version, so my fix is no need.

**Comment by anandology** [comment]
@bigzhu it is still an issue with Python 2. I'm able to successfully reproduce the issue. It is not an issue with Python 3 though. 

Here is code to reproduce it.

	import web

	db = web.database(dbn="postgres", db="rx-datasets")

	d1 = {"x": 1, "y": 2, "z": 3}

	d2 = {i:i for i in range(1000)}
	d2.update(d1)
	for i in range(1000): del d2[i]

	db.multiple_insert("test2", [d1, d2])

I'll look into this issue shortly.

**Pull request closed without merging**
