### PR TITLE
Add comment line to bypass Black format if URLs contain multiple patterns.

### PR DESCRIPTION
**Pull request by iredmail**
Add comment line `# fmt: off` for `urls = ()` which contain multiple patterns to bypass Black formatter.

### CODE REVIEW

**Comment by cclauss** [comment]
Thanks but, don’t you need to balance these with __# fmt: on__ or do I misunderstand.

**Comment by iredmail** [comment]
For those `urls = ()` with only one url pattern like this:

```
urls = (
    '<pattern>', 'class-or-func'
)
```

it will be formatted to:

```
urls = ('<pattern>', 'class-or-func')
```

It's short and no readability issue at all, so we will let Black reformat it.

**Comment by iredmail** [comment]
Just added the missing `# fmt: on`. Sorry about this stupid mistake.

**Comment by iredmail** [comment]
Feel free to merge it and rebase your PR. :)

**Pull request merged**
