### PR TITLE
Clarify TypeError if layout.html does not start with '$def with (content)'

### PR DESCRIPTION
**Pull request by cclauss**
Partial fix for #612 but we also need a test that shows that the proper exception will be raised.

### CODE REVIEW

**Comment by cclauss** [comment]
We still raise a TypeError so this is not a warning but the message is more helpful.

I do not know how to add the test.

**Comment by iredmail** [comment]
Hmm, I replied too quick. Some concerns of this change:

- the variable name “content” could be any name. The “print()” line may implicitly advice users to use just “content”.

- Seems this change checks all template files, not just layout file. So the text in “print()” may mislead user to check just layout.html. 

- Will “TypeError” also catch other errors?

**Comment by cclauss** [comment]
The try / except block will __only__ catch TypeErrors.

**Comment by iredmail** [comment]
This PR is not correct.

- The `except` is added in wrong place.
- Other errors may raise `TypeError` exception too, so the text in `print()` is incorrect.

I will send a new PR for this.

**Comment by iredmail** [comment]
There're at least 3 different errors might be raised while rendering a template file, and it could happen to any template file, not just the layout.html, so the text in your `print()` is imprecise.

Proposal:

- Update [templator document](https://webpy.org/docs/0.3/templetor), list all possible errors and the solution for each error.
- Catch `TypeError` and `NameError` in your PR, print text with a link to the document. For example:

```
        try:
             return self.t(*a, **kw)
         except (TypeError, NameError) as e:
             print("Check web.py website to check possible errors and how to fix it: https://webpy.org/docs/0.3/templetor#errors
             raise e
```

#### `TypeError: __template__() got an unexpected keyword argument 'myvar'`

The `render` calls the template file with unexpected keyword argument `myvar`.

Template file:
```
$def with (var1, var2)

My content:
$:var1
$:var2
```

Python code.

```
import web
render = web.template.render()

# WRONG. `myvar` should be removed.
print(render.my_template_file(var1=..., var2=..., myvar=...))

# CORRECT.
print(render.my_template_file(var1=..., var2=...))
```

#### `TypeError: __template__() takes 0 positional arguments but 1 was given`

Template file doesn't have `$def with (...)` line (which indicates it doesn't use any variables), but 1 variable name is passed to the template while calling the `render` function.

Template file:
```
My sample content here without using any variable.
```

Python code:

```
# WRONG.
print(render.my_template_file(myvar=...))

# CORRECT.
print(render.my_template_file())
```

#### `TypeError: __template__() missing 1 required positional argument: 'myvar'`

Template file uses variable name `myvar`, but it's not passed while calling the `render`.

Template file:

```
$def with (myvar)

Render the value:
$:myvar
```

Python code.
```
# WRONG.
print(render.my_template_file())

# CORRECT
print(render.my_template_file(myvar=...))
```

**Comment by cclauss** [comment]
Closing.  Please create a PR to replace it.

**Comment by iredmail** [comment]
@cclauss could you help create a new PR? Just change the text in the “print()” should be enough. :)

**Comment by cclauss** [comment]
I would encourage you to do...
```python
try:
    ABC
except NameError as e:
    print("Message about NameErrors")
    raise e
except TypeError as e:
    print("Message about TypeErrors")
    raise e
```

**Comment by cclauss** [comment]
If you create the PRthen I can review it.

**Pull request closed without merging**
