### PR TITLE
Add redis-based session store

### PR DESCRIPTION
**Pull request by iamFIREcracker**
With this commit I would like to introduce a new session store based on Redis.  This store creates a sorted set with key `webpy.sessions` containing all the id of all the active sessions, and a key with name`webpy.session:$ID` containing the data associated with the active session.

### CODE REVIEW

**Comment by jzellman** [comment]
I like the idea and could see myself using something like this. I do have a couple concerns with this PR though. web.py is meant to be small and simple. This adds a dependency/complexity to web.py on a particular redis library that supports things like zrem(?), etc. This PR also opens the door to supporting any other session store, like amazon S3, berkley db, memcache. The build also fails with no provided tests. 

Maybe this could be better suited in the cookbook as a sample of how to build your own custom SessionStore? Or maybe it belongs in the experimental or contrib directory? Another idea would be to have a separate project, say web.py extras where things like this could live. Thoughts?

**Comment by iamFIREcracker** [comment]
I don't have a strong opinion on this, so just tell me what do you prefer me to do (eg. convert this into a cookbook example, move it somewhere inside experimental/contrib).

Once upon a time I created a repository[0] with a bunch of web.py related things that I constantly found myself in need of when starting a new project; if you find some of those things interesting I could create small PRs and try to get them merged -- but again, we might want to find a new home for all this stuff first (be it the experimentarl/contrib folder, or a new official repo)

[0] https://bitbucket.org/iamFIREcracker/weblib/src/7d0975cec10e?at=default

**Comment by dmmartins** [comment]
I agree with the cookbook redis example or a generic example on how to write your own session store. I think you should put your work in a repo, though. Using redis as session store is very common and more people can use that. Just maybe not as part of core web.py.

Also as a suggestion, the 'webpy.session:*' key can be a default value but you should be able to use a different value.

BTW you repo weblib is not public.

**Comment by iredmail** [comment]
No plan to implement Redis based session store yet, feel free to make it as a third-party repo for further use.

**Pull request closed without merging**
