### PR TITLE
Start testing on Python 3.9 and stop on EOL Py3.5

### PR DESCRIPTION
**Pull request by cclauss**
* https://devguide.python.org/devcycle/#end-of-life-branches
* https://devguide.python.org/#status-of-python-branches

### CODE REVIEW

**Comment by iredmail** [comment]
Debian 9 ships 3.5 and it’s still widely deployed, I suggest keeping 3.5 support for at least 1-2 years.

**Comment by iredmail** [comment]
@cclauss really drop 3.5? I hope to keep it for 1-2 years.

**Comment by cclauss** [comment]
I was hoping that we could move to f-strings ;-)

**Review by iredmail — APPROVED** [review]
README.md should update version number to 0.62 or 0.7.

**Pull request merged**
