### PR TITLE
Remove trailing whitespace

### PR DESCRIPTION
**Pull request by blueyed**
Used:

    sed -i 's/ \+$//' **/*.py

### CODE REVIEW

**Comment by blueyed** [comment]
Is this something that is wanted?
I can re-do it then again to fix conflicts, but feel free to do it yourself, of course.

**Comment by cclauss** [comment]
Please fix conflicts.

**Comment by blueyed** [comment]
Would just redo it.
Would prefer to do it after https://github.com/webpy/webpy/pull/485 to ensure there are no unexpected things happening.

**Comment by blueyed** [comment]
Rebased/redone.

**Comment by cclauss** [comment]
There seems to be a better way to achieve this that is built into every installation of CPython...
* https://github.com/python/cpython/blob/master/Tools/scripts/reindent.py

**Comment by blueyed** [comment]
@cclauss 
It is not about reformatting, but only about removing trailing whitespace in one step (i.e. a minimal change).

**Comment by cclauss** [comment]
Next step would be to pass the codebase thru https://GitHub.com/python/black

**Comment by blueyed** [comment]
@cclauss 
Won't do it myself - not using webpy anymore.

**Comment by iredmail** [comment]
@cclauss reformatting is not urgent. Maybe we should release a new stable version first, then drop py2 support since it will be EOF on Jan 1, 2020, get rid of the burden and move on.

**Pull request merged**
