### PR TITLE
Travis CI: Add Python 3.9

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by iredmail** [comment]
Can we give Debian 9 users a chance to use new web.py release?
https://github.com/webpy/webpy/pull/682

**Comment by cclauss** [comment]
Yes.  I would like to make a release after #690 and this PR land.  Nono of these changes will prevent the software from working on Python 3.5...  They just do not explicitly test on Python 3.5.

**Comment by iredmail** [comment]
The `setup.py` was updated to require 3.6:

**Comment by cclauss** [comment]
OK.  Now I understand.  Let's create two releases:
1. Release v0.62 will include #690 plus this PR (with Python 3.5 added back in setup.py).  v0.62 will be our last release which supports Python 3.5.
2. Release v0.70 which will drop support for Python 3.5 and include [`pyupgrade --py36-plus`](https://github.com/asottile/pyupgrade) changes.

**Comment by iredmail** [comment]
ok. That's perfect.

**Comment by cclauss** [comment]
Your review please.

**Review by iredmail — APPROVED** [review]

**Pull request merged**
