### PR TITLE
Should we add The web.py Philosophy to README.md?

### PR DESCRIPTION
**Pull request by cclauss**
From http://webpy.org/philosophy

### CODE REVIEW

**Comment by iredmail** [comment]
It's good to have it in README.md.

This part was wrote by original author, Aaron, i think we have to rewrite it somehow to make it better for current situation. for example, i don't think it's good to write `This is literally how __I__ developed web.py.` Also, make it more serious to introduce a product.

**Comment by cclauss** [comment]
I actually like the text in Arron's voice...  It talks directly to the developer in a way that is unique.

I would be interested in the views of @anandology and @sbp who have lived more of the history.

**Comment by iredmail** [comment]
Then maybe add something LIKE "Said by original developer/founder, Aaron, ..." and quote the text below?

**Comment by iredmail** [comment]
Hi @cclauss 

I suggest we add only this line to the README.md, then close this PR:

```
_Think about the ideal way to write a web app. Write the code to make it happen._
```

**Pull request closed without merging**
