### PR TITLE
Implemented fix for issue 461 unicode in request url

### PR DESCRIPTION
**Pull request by schneidersoft**

### CODE REVIEW

**Comment by cclauss** [comment]
Oh...  Tests failing on legacy Python.

**Comment by iredmail** [comment]
So many tests failed. @schneidersoft, could you please update your PR?

**Comment by schneidersoft** [comment]
'/%E2%84%A6' is /Ω url encoded and b'\xE2\x84\xA6'==u'Ω'.encode('utf8').
To use Ω directly would mean adding a dependency to urllib... I'm just avoiding that

**Comment by iredmail** [comment]
Thank you for the contributions, @schneidersoft, @cclauss. :)

**Pull request merged**
