### PR TITLE
Add a GitHub  Action to lint and test Python code

### PR DESCRIPTION
**Pull request by cclauss**
As discussed at https://github.com/webpy/webpy/issues/587#issuecomment-595049821

isort is run in _allow failures_ mode.

### CODE REVIEW

**Comment by iredmail** [comment]
I suppose we should run `black --check .` (the one used in `.travis.yml`) instead of `black . --diff || true`?

**Comment by cclauss** [comment]
Too late...  Already done.

**Comment by iredmail** [comment]
hi @cclauss 

Could you enable test for py 3.6 and 3.7 also, some Linux distributions ship these py releases:

- RHEL/CentOS 7 and 8: 3.6.8
- OpenBSD 6.6: 3.7.4
- Debian 10, Ubuntu 18.04: 3.7, 3.8

**Comment by iredmail** [comment]
Well done @cclauss. 
Feel free to merge this PR if finished. :)

**Comment by anandology** [comment]
@cclauss thanks for the prompt action! We need to setup postgres and mysql containers as part of the github action to be able to test against them.

**Comment by cclauss** [comment]
Sorry @anandology I have left the service for mysql and postgres commented out because I do not know enough about these DBs to make them install and run.

**Pull request merged**
