### PR TITLE
Add auto-generated unit tests for improving code coverage

### PR DESCRIPTION
**Pull request by WenhaoSu**
This is a PR from the developers of the [Pyster tool](https://github.com/WenhaoSu/pyster). We are students from University of Illinois at Urbana-Champaign, and Pyster is a course project of CS527 - Topics in Software Engineering. Pyster is a framework that allows coverage-driven automated unit test generation for Python.

We ran our tool on this repository and found several places where there was low code coverage. These additional tests were added by looking at those spots of low coverage and trying to improve them. Below is a figure showing the improved coverage after adding those tests.

image

All those tests are automatically generated by our black-box tool. We're willing to help if you found those tests might be helpful in improving code coverage and want them to be reformatted somehow! Below is a list of coverage improvement for different modules:

| Module Name | Coverage Before | Coverage After |
| -------- | -------- | -------- |
| `browser.py`     | 59.18%     | 70.07%     |
| `db.py`          | 59.48%     | 66.70%     |
| `form.py`        | 42.68%     | 66.36%     |
| `http.py`        | 35.53%     | 40.79%     |
| `heepserver.py`  | 27.57%     | 35.14%     |
| `net.py`         | 34.29%     | 46.67%     |
| `py3helpers.py`  | 33.33%     | 66.67%     |
| `session.py`     | 75.19%     | 82.56%     |
| `utils.py`       | 32.64%     | 44.02%     |
| `utils.py`       | 32.64%     | 44.02%     |
| `webapi.py`      | 66.78%     | 82.03%     |
| `wsgi.py`        | 35.71%     | 40.48%     |

### CODE REVIEW

**Comment by iredmail** [comment]
I think it's better run Pyster in CI instead of adding the auto-generated unit tests in source code. :)
Ping @cclauss @anandology

**Comment by cclauss** [comment]
My sense is that these are static changes that can be applied one time if at all.  It is impressive that the tests can be autogenerated but I wonder if they help us detect flaws or if they are more targeted at placating codecov.  @okken, @mikeckennedy do you know the Pyster tool?  Thoughts on the quality/utility of these autogenerated tests?

**Comment by anandology** [comment]
While I appreciate the efforts went into Pyster tool, I don't see any value
in the tests generated by that tool for web.py.

**Comment by anandology** [comment]
@WenhaoSu Pyster looks like a very cool hack, but I'm not a big fan of code
generation and I don't see the generating tests helping in web.py in any
way.

**Comment by okken** [comment]
@cclauss I hadn't seen the tool before. 
The generated tests for this project are almost all (if not all) related to making sure certain functions raise expected exceptions.
For a pytest based test suite, I'd expect the code to use `with pytest.raises(expectedException):`, instead of try/except blocks. It would make the intent of the test more clear.

On the wider topic of "are auto generated tests any good", I don't have enough experience with them to have an opinion. I've never felt the need for auto generated tests.

Also, thanks for asking. It's an interesting topic.

**Comment by WenhaoSu** [comment]
@iredmail @cclauss @anandology @okken Thanks for all your replies! As Pyster is a newly developed tool and is still in the experimental stage, all your opinions are extremely valuable feedback to us! We'll try to focus more on the quality of the generated tests as well as the ability to detect potential flaws in the source code, and make Pyster a more supportive tool.

Again, thanks a lot for all your time and supports! :)

**Pull request closed without merging**
