### PR TITLE
Update ChangeLog.txt based on commit history.

### PR DESCRIPTION
**Pull request by iredmail**

### CODE REVIEW

**Comment by iredmail** [comment]
Dear @cclauss @anandology 

- I think it's time to release a new (py3 only) release due to issue #644. If users are moving their app from 2 to 3, they will have this issue with session support.
- Version number might be `0.6x` or `1.0`, either is ok to me.

**Comment by cclauss** [comment]
My sense is that v1.0 should drop support for legacy Python.  All versions < v1.0 support legacy Python.

**Comment by iredmail** [comment]
Then we go v1.0. :)

**Comment by iredmail** [comment]
Hi @anandology, would you like to publish a new release to pypi?

**Comment by anandology** [comment]
> Then we go v1.0. :)

I don't think we are ready for 1.0.

**Comment by anandology** [comment]
> Hi @anandology, would you like to publish a new release to pypi?

Could you please take care of this? I guess you have all the permissions.

**Comment by iredmail** [comment]
@anandology

- What’s missing in your opinion?  Since py2 is dead for half a year, people are looking for moving to py3 seriously, but the latest webpy 0.51 is buggy due to the issue I mentioned in 2nd reply here, we need a new release to satisfy them. 

- last time I messed up pypi release, and caused some Linux/bsd package maintainers refused to package the new version.
- you didn’t help finish the document yet, I don’t have any pypi packages myself, didn’t practice yet, do if you don’t mind, take over this job.

**Comment by anandology** [comment]
On Tue, Jul 21, 2020 at 4:15 PM iRedMail <notifications@github.com> wrote:

> @anandology <https://github.com/anandology>
>
>    -
>
>    What’s missing in your opinion? Since py2 is dead for half a year,
>    people are looking for moving to py3 seriously, but the latest webpy 0.51
>    is buggy due to the issue I mentioned in 2nd reply here, we need a new
>    release to satisfy them.
>    -
>
>    last time I messed up pypi release, and caused some Linux/bsd package
>    maintainers refused to package the new version.
>    -
>
>    you didn’t help finish the document yet, I don’t have any pypi
>    packages myself, didn’t practice yet, do if you don’t mind, take over this
>    job.
>
>
Sure, I'll push the release tonight.

**Comment by anandology** [comment]
I'm confused about the `py2` branch. Are we making releases on a branch instead of master?

Does that mean are we maintaining two separate branches now?

**Comment by iredmail** [comment]
Sorry about the confusion, it was created by me.

- The `py2` branch is used to maintain old `0.5x` release branch, if there's any urgent + critical bugs, we release new `0.5X` release in the `py2` branch.
- All further development should happen in `master` branch, including new releases.

**Comment by anandology** [comment]
The current release is on py2 branch? or on master?

I think we should release 0.6 with python3 only support and move toward 1.0
development from there.

**Comment by iredmail** [comment]
> The current release is on py2 branch? or on master?

The latest stable release is `0.51` on `py2` branch.
Upcoming release drops py2 support, it must be on `master` branch, not `py2` branch.

> I think we should release 0.6 with python3 only support and move toward 1.0 development from there.

Any version number is ok for me. `0.60` is ok too.
We should add a serious + discussed roadmap for 1.0 and focus on it.

**Pull request merged**
